---

- name: Create folder for Multus resource defs
  file:
    path: "{{ ansible_env.HOME }}/multus-resources"
    state: directory

- name: Template multus resources
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/multus-resources/{{ item.dest }}"
  with_items:
    - src: crd.yml.j2
      dest: "multus-crd.yml"
    - src: flannel.yml.j2
      dest: "flannel.yml"
    - src: macvlan.yml.j2
      dest: "macvlan.yml"

- name: Check to see if CRD is present
  shell: >
    kubectl get crd
  register: check_crd

- name: Create base CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/multus-crd.yml
  when: "'networks.kubernetes.com' not in check_crd.stdout"

- name: Check to see which network CRD definitions are present
  shell: >
    kubectl get networks
  register: check_network_crds

- name: Create flannel network CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/flannel.yml
  when: "'flannel-conf' not in check_network_crds.stdout"

- name: Create macvlan network CRD
  shell: >
    kubectl create -f {{ ansible_env.HOME }}/multus-resources/macvlan.yml
  when: "'macvlan-conf' not in check_network_crds.stdout"

- name: Get the clusterrolebindings
  shell: >
    kubectl get clusterrolebindings
  register: output_crb

- name: Create clusterrolebindings for each machine
  shell: >
    kubectl create clusterrolebinding multus-node-{{ hostvars[item]['inventory_hostname'] }}
    --clusterrole=system:node
    --user=system:node:{{ hostvars[item]['inventory_hostname'] }}
  with_items:
    - "{{ groups['nodes'] + groups['master'] }}"
  when: >
    "hostvars[item]['inventory_hostname']" not in output_crb.stdout